"""empty message

Revision ID: 1092ff074d7d
Revises: 1fce6d5dccd2
Create Date: 2014-08-21 00:53:05.963785

"""

# revision identifiers, used by Alembic.
revision = '1092ff074d7d'
down_revision = '1fce6d5dccd2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
