"""butts

Revision ID: 2279454acd0
Revises: 1092ff074d7d
Create Date: 2014-08-21 01:01:27.902439

"""

# revision identifiers, used by Alembic.
revision = '2279454acd0'
down_revision = '1092ff074d7d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
