"""

Revision ID: 22cd0697475c
Revises: 2ee832f7e6d0
Create Date: 2014-08-21 01:10:24.812139

"""

# revision identifiers, used by Alembic.
revision = '22cd0697475c'
down_revision = '2ee832f7e6d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
