"""Moar Butts

Revision ID: 2ee832f7e6d0
Revises: 2279454acd0
Create Date: 2014-08-21 01:09:57.623815

"""

# revision identifiers, used by Alembic.
revision = '2ee832f7e6d0'
down_revision = '2279454acd0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
