"""

Revision ID: 4477a01c7700
Revises: 22cd0697475c
Create Date: 2014-08-21 01:12:06.488260

"""

# revision identifiers, used by Alembic.
revision = '4477a01c7700'
down_revision = '22cd0697475c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
